print("Lets register")
register = input("Enter your name: ")
register2 = input("ENter your last name: ")
register3 = input("Enter your login word: ")
register4 = input("Enter your password: ")
register5 = input("Repeat password: ")
while register4 != register5:
    print("Passwords doesnt match")
    register4 = input("Enter your password: ")
    register5 = input("Repeat password: ")
print("Now lets login!")
login = input("Enter your login: ")
while login != register3:
    print("Incorrect login!")
    login = input("Enter your login: ")
login1 = input("Enter your password: ")
while login1 != register4:
    print("Incorrect password")
    login1 = input("Enter your password: ")
print("Wellcome to your account", register, register2)