user_name = input('Enter your name: ')
user_last_name = input('Enter your last name: ')
user_city = input('Enter your city: ')
user_fav_color = input('Enter your favourite color: ')
user_fav_food = input('Enter your favourite food: ')
print('Hello', user_name, user_last_name, 'You live in', user_city, 'Your fav color is', user_fav_color, 'Your favourite food is', user_fav_food)