name = input("Whats your name?:")
age = input("how old are you?:")
last_name = input("whats your last name?:")
city = input("whats your city?:")
print("hello!", name, "you are", age, "years old, your city is", city, "and your last name is", last_name)